
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class platformmovement : MonoBehaviour
{
    [SerializeField] GameObject[] Waypoints;
    int currentWaypointIndex = 0;

    [SerializeField] float speed = 1f;
    
    void Update()
    {


        if(Vector3.Distance(transform.position,Waypoints[currentWaypointIndex].transform.position) < .1f)
                {

            currentWaypointIndex++;
            if (currentWaypointIndex > Waypoints.Length)
            {

                currentWaypointIndex = 0;
            
            
            }
                    


                }

        transform.position = Vector3.MoveTowards(transform.position, Waypoints[currentWaypointIndex].transform.position, speed * Time.deltaTime);


 
    }








}

